### ISSUE TITLE
Unhelpful type error dynamic can't be assigned to String for `$event`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#165]
```html
<material-input (ngModelChange)="update($event)"
```
and
```dart
void update(String value) {
```
causes
```
ERROR: The argument type 'dynamic' can't be assigned to the parameter type 'String'. ([fhir_client] lib/designer/webui/input/text_input_component.html:8)
```

Changing the parameter type to `dynamic` isn't too helpful in my opinion.

**Comment by MichaelRFairhurst** [comment]
I think the problem here is because of pub transformers.

I believe if you put CORE_DIRECTIVES in the directives list of the component, it will go away. Pub transformers do this for you, but the analyzer doesn't pick up on that yet.

That said, this is strange. Dynamic _should_ be assignable to String. I'd expect it to not recognize the event, report an error for that, and then it sets `$event` to dynamic with the purpose being of preventing secondary errors (`$event` should be considered uncheckable until the output binding is corrected). Clearly that purpose isn't working.

Does the error go away if you add CORE_DIRECTIVES?

**Comment by zoechi** [comment]
You are right these are now gone as well. Sorry again for the noise.

**Comment by MichaelRFairhurst** [comment]
Actually I'm going to leave this one open because, like I said, the error state shouldn't have secondary errors. This one is weird to me and I'd like to look further into it.

And thank you again for filing so many issues!

**Comment by MichaelRFairhurst** [comment]
I think this secondary error was caused by having implicit-downcasts disabled, which is fine.
