### ISSUE TITLE
`ngFor` `index` variable not recognized

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#166]
```html
<tr *ngFor="let item of data; let index=index" [class.is-selected]="index == selectedIndex">
```
causes
```
ERROR: Undefined name 'index'. ([fhir_client] lib/designer/webui/list/list_component.html:3)
```

**Comment by zoechi** [comment]
Also the `ngFor` variable is not recognized

```html
<resource-search-parameter
    *ngFor="let param of searchResult.search?.params"
    [searchParam]="param"
    [resourceType]="resourceType">
</resource-search-parameter>
```
```
ERROR: Undefined name 'param'. ([fhir_client] lib/webui/practitioner_app/practitioner_search_component.html:3)
```

**Comment by MichaelRFairhurst** [comment]
Once again, I believe you need to add CORE_DIRECTIVES. Let me know if that solves it

**Comment by zoechi** [comment]
I think you are right. Sorry, I should have revisited the bugs I reported at the end.

**Comment by zoechi** [comment]
I was a bit confused because sometimes the number of errors dropped from about 350 to 20 and then they eventually came back. Now they are gone for good because killing the analyzer doesn't bring them back.

**Comment by MichaelRFairhurst** [comment]
No problem! Thank you for documenting all these issues, it clearly took you a lot of time and even a duplicate bug says something about the original :)

Yeah, the transformers are a HUGE missing feature for...basically everyone but us who use it internally. As these bugs go to show. Unfortunately its not a top priority for us right now because it has a workaround. But I should probably at the very least add at it as a big bold disclaimer in the readme...

**Comment by zoechi** [comment]
> But I should probably at the very least add at it as a big bold disclaimer in the readme...

That could save you from a load of bug reports :D

> Yeah, the transformers are a HUGE missing feature for.

If there were some Bazel support without transformers in sight for us mere mortals, this probably  wouldn't matter that much. Sadly it's so difficult to extort some timelines from Googlers ;-)
