### ISSUE TITLE
Underline highlighting showing linter warning at wrong place

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#241]
![image](https://cloud.githubusercontent.com/assets/405837/22260965/7d2ce8be-e26b-11e6-941b-d90a74624027.png)

**Comment by zoechi** [comment]
Linux. Line endings != `\n` are quite unlikely.

**Comment by MichaelRFairhurst** [comment]
Kinda hard to tell at first, but looks like the error here starts at the end of where it should. That also would be a bit coincidental for line ending-related problems.

Its like we're doing `new AnalysisError(token.offset + token.length, token.length)` instead of `new AnalysisError(token.offset, token.length)`.

**Comment by zoechi** [comment]
I haven't seen this for quite some time.
