### ISSUE TITLE
Dedupe suggestions based on directive.classElement

### ISSUE THREAD

**Issue by mk13** [dart-lang/angular_analyzer_plugin#328]
Ex: NgIf appearing twice if NgIf and CORE_DIRECTIVES imported.

**Comment by MichaelRFairhurst** [comment]
should be able to just dedupe on `d1 == d2`, `AbstractDirective` overloads `==` to check the underlying `classElement`.

Alternatively, we can put them into a `Set` instead of a `List` so they dedupe themselves.

**Comment by mk13** [comment]
I used the set method :)

**Comment by mk13** [comment]
Resolved for inputs PR #343, but will keep open since this will be persistent once attribute-directive will need deduping as well.

**Comment by MichaelRFairhurst** [comment]
I think we should dedupe this right at the source:

```
directives: [NgIf, CORE_DIRECTIVES]
```

this should result in a `Component` with `.view.directives` of `[NgIf,
NgFor, NgForm]`, no duplicates. We should be able to do this by just making
`View.directives` a `Set`.

Otherwise, everything will be duplicated. For instance, `<div *ngIf="1">`
will probably show two errors, send two navigation items, report two usages
in the search, perhaps mess up refactoring......

**Comment by mk13** [comment]
That sounds like a good plan.

**Comment by mk13** [comment]
Done.
