### ISSUE TITLE
A component and a directive from the same file caused `type_is_not_a_directive

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#353]
![image](https://cloud.githubusercontent.com/assets/405837/26393207/667754ea-4069-11e7-9bb4-8fae051b1b67.png)

moving the directive to another file solves the error

```
Dart VM version: 1.24.0-dev.5.0 (Fri May 19 01:41:50 2017) on "macos_x64"
```

**Comment by zoechi** [comment]
![image](https://cloud.githubusercontent.com/assets/405837/26393760/1f50f18c-406b-11e7-8a26-0b788943f4f2.png)

This is another case but here it's not about more than one directive within one file. 
I haven't found anything about what might cause it.

**Comment by MichaelRFairhurst** [comment]
This is strange because I think all of our multi component tests except maybe two involve declaring two components in one file.

Regarding the other one that's causing the error, what's the import directive? Does it use a relative or absolute uri, does it have any `show`/`hide`s, etc?

Also its possible that it has some errors in it which prevent it from being saved into the directives list. We had this issue before where an error in the selector would cause places that use it to report that its not a directive, for instance, though that exact issue is fixed.

**Comment by zoechi** [comment]
It's really weird. I have encountered this problem only in one project so far. 
I fixed everything the analyzer complained about and I wasn't able to find anything else that might be wrong. There are no show/hides used.
I'll keep observing and post updates when I find out more.

**Comment by zoechi** [comment]
that's a dup of #376
