### ISSUE TITLE
type literal expected

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#376]
![image](https://user-images.githubusercontent.com/405837/27177866-3546cfde-51c8-11e7-98ac-4e644b93a447.png)

I get about 40 such warnings when I install the plugin.

Dart VM version: 1.25.0-dev.0.0 (Mon Jun 12 10:40:27 2017) on "macos_x64"

**Comment by MichaelRFairhurst** [comment]
And no other warnings, like, unrecognized identifier or non const argument?

This means we couldn't determine it to be a class.

How is it imported? Anything special?

**Comment by zoechi** [comment]
I haven't found anything special about these yet. 
The code works fine and if the plugin is not installed, I don't get these warnings.

**Comment by zoechi** [comment]
I had such warnings occasionally in the past but doing some editing made them go away.
Since recently these warnings are permanent though.

**Comment by mk13** [comment]
Do you see .html errors for undefined tags when you try and use the selector for these Component classes?

**Comment by zoechi** [comment]
Yes, for the tags I get 'unresolved tag "the-tag-name"'

**Comment by mk13** [comment]
I'm having a difficult time reproducing this issue. Did you use build version one or version two?

**Comment by zoechi** [comment]
How can I distinguish these two?

**Comment by zoechi** [comment]
I'm using version 1. 
The readme says version 2 isn't yet usable.

**Comment by mk13** [comment]
When was the last time you re-built the analyzer? I'll try and investigate this ASAP, but I'm a bit low on bandwidth atm.

**Comment by zoechi** [comment]
I tried today. It's still the same.
Now with
Dart VM version: 1.25.0-dev.1.0 (Wed Jun 14 08:05:56 2017) on "macos_x64"

**Comment by MichaelRFairhurst** [comment]
Gunter, can you try clearing out

~/.dartServer/.analysis-driver/*.ng*

and rerun analysis, make sure its still there?

**Comment by zoechi** [comment]
Looks like that fixed it.
Thanks a lot for the investigation!

**Comment by sgon00** [comment]
Hi, I meet a similar error message today. When I was learning angulardart and following tour_of_heros tutorial today. VSCode reports `formDirectives` with warning message `A type literal expected`. 

By quitting everything, then executing `rm ~/.dartServer/.analysis-driver/*.ng*` and restart everything, the warning is gone. I am wondering what the true cause of this problem is. It's definitely a bug. It's not right to ask users to `rm ~/.dartServer/.analysis-driver/*.ng*` manually randomly. I have no idea what's wrong. 

Version: `Dart VM version: 2.1.1-dev.3.2 (Thu Jan 24 11:50:07 2019 +0100) on "macos_x64"`

**Comment by diver2** [comment]
running on the same warning message here, Dart 2.1.1 stable.
just trying to use my first <material-button>

**Comment by sgon00** [comment]
I am meeting this again today. The weird part is I have two VSCode instances (projects/directories) opened. One reports error on `formDirectives` and another instance doesn't report the error. This is just weird. I have to `rm` and restart again...

**Comment by vision8tech** [comment]
Indeed, removing `*.ng*` from `~/.dartServer/.analysis-driver/` is not the solution, but the workaround 'til the issue is fixed.

Another interesting thing is that in the same location looks like that currently I have huge number of files, currently having **124397** of .linked or .unlinked or .resolved files that are never cleaned up:

```bash
user@host:.analysis-driver $ rm ~/.dartServer/.analysis-driver/
Display all 124397 possibilities? (y or n)
```
<br/>

First (oldest) entries that I have are in a number of **1484** entries created in the same one minute:
```bash
user@host:.analysis-driver $ find . -newermt "2018-12-29 14:42" ! -newermt "2018-12-29 14:43" | wc -l
    1484
$
```
