### ISSUE TITLE
analyzer doesn't start anymore in IntelliJ

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#392]
After updating today the analyzer stopped working in IntelliJ. I don't even get an error message.
When I run the analyzer snapshot I get

> Wrong script snapshot version, expected '14440271548947b61da9c593e625028d' found 'ea47fe5aff892a77628dbe3ae4ab9247'

Does the installation procedure need to be changed?

**Comment by MichaelRFairhurst** [comment]
I think this means you built the snapshot with a different SDK version that you're running it with. Can you check?

**Comment by zoechi** [comment]
It looks like `make_snapshot` was moved

from 
```
server_plugin/bin/make_snapshot
``` 
to 
```
old_plugin_loader/bin/make_snapshot
``` 

and therefore the previously generated snapshot was copied into the `bin/snapshots` directory.

So it seems a different installation procedure is required.

**Comment by MichaelRFairhurst** [comment]
Ah, yes. Will update the readme soon.

On Jul 15, 2017 9:57 AM, "Günter Zöchbauer" <notifications@github.com>
wrote:

It looks like make_snapshot was moved

from

server_plugin/bin/make_snapshot

to

old_plugin_loader/bin/make_snapshot

and therefore the previously generated snapshot was copied into the
bin/snapshots directory.

So it seems a different installation procedure is required.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/angular_analyzer_plugin/issues/392#issuecomment-315547187>,
or mute the thread

**Comment by MichaelRFairhurst** [comment]
Hmm, looks like the instructions already say to use `old_plugin_loader`.

Have you solved your issues related to the move, anything else I can do to keep it working for you?

**Comment by zoechi** [comment]
I missed that change.
Is working fine. Thanks!
