### ISSUE TITLE
Pipe class inheriting a transform method should be ok

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_analyzer_plugin#533]
A pipe class can inherit its transform method, can it not? Angular seems to be happy with this, but the plugin reports an issue:

> warning: @Pipe declared classes must contain a 'transform' method
>
> <img width="409" alt="screen shot 2018-03-29 at 18 18 37" src="https://user-images.githubusercontent.com/4140793/38116394-dad2a3c8-337d-11e8-9524-1c698b60dc03.png">

cc @kwalrath @matanlurey

**Comment by MichaelRFairhurst** [comment]
Yep, inheritance should be fine!

We likely record offset information about it in the tree, so we're probably looking at the source instead of the class's interface. I should be able to add a fall back that operates in other ways, or even always go off of the interface and just change how to get the offset info to something more clever.

Thanks for filing!
