### ISSUE TITLE
publish a new angular_analyzer_plugin

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/angular_analyzer_plugin#595]
to capture the latest work; in particular, the current dev sdk no longer contains upper case constants, and the last published version of this package still uses them.

**Comment by devoncarew** [comment]
For context, here's what I see when running with the latest sdk:

```
IsolateSpawnException: Unable to spawn isolate: file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/angular_analyzer_plugin-0.0.16/lib/src/angular_driver.dart:438:26: Error: Getter not found: 'UTF8'.
    final contentBytes = UTF8.encode(getFileContent(path));
                         ^^^^
file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/angular_analyzer_plugin-0.0.16/lib/src/angular_driver.dart:438:26: Error: The getter 'UTF8' isn't defined for the class '#lib1::AngularDriver'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'UTF8'.
    final contentBytes = UTF8.encode(getFileContent(path));
                         ^
file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/angular_analyzer_plugin-0.0.16/lib/src/summary/format.dart:121:32: Error: Getter not found: 'JSON'.
  String toString() => convert.JSON.encode(toJson());
```

**Comment by devoncarew** [comment]
@MichaelRFairhurst, it looks like this is done (we published 0.0.17)? Can you make a release (https://github.com/dart-lang/angular_analyzer_plugin/releases) for whatever commit this was done at? Thanks!

**Comment by devoncarew** [comment]
It looks like users, who previously had angular installed, will be getting an older version of the plugin which is not happy w/ Dart 2 VMs.

I think we need to update this line: https://github.com/dart-lang/angular/blob/master/angular/tools/analyzer_plugin/pubspec.yaml#L7

to have an explicit dep on `0.0.17`.

@bwilkerson, we should also think about when and how we could have the analyzer plugin mechanism run pub upgrade on plugins and their deps.

**Comment by bwilkerson** [comment]
Looking at `PluginManager._computePaths`, it looks like we ought to be running `pub get` the first time we see a plugin and `pub update` every time we attempt to start it after that. It's quite possible that there's a bug in this code that's preventing `update` from being run, though.

**Comment by MichaelRFairhurst** [comment]
0.0.17 has already been published.

The constraint inside angular *should* be updated, but doesn't need to be since it specifies '^'. The pub solver should choose 0.0.17 for everyone, especially if their SDK version requires 0.0.17, pub will figure that out.

I have noticed that pub upgrade doesn't always work. I landed that and tested it, and it seemed reliable at first but since I've had issues with it not succeeding and I'm not sure why.

**Comment by bwilkerson** [comment]
It's possible that upgrade can't upgrade because of a problem in the version constraints. Should be easy enough to figure out, though, by manually running `pub upgrade` in the bootstrap plugin to see which versions it chooses. If `upgrade` works when run manually, then we know we have a bug in our server code.

**Comment by tenhobi** [comment]
Not sure if this helps, but here's what I tried: I have removed the pub cache and the .dartServer and tried to run `pub get` again and the issue was fixed for me. So it's true the updating system has some issues.

**Comment by MichaelRFairhurst** [comment]
I will close this, but the update code definitely needs to be fixed and I'll be taking a look at that under a different issue.

Thanks everyone!
